name: packageInstall
description: install pnpm package
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: using node 16.13.0
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0

    - uses: pnpm/action-setup@v2
      name: Install pnpm

    - name: module install
      shell: bash
      run: pnpm i --frozen-lockfile
