root: true
env:
  es6: true
  node: true
  browser: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:storybook/recommended
  - next/core-web-vitals
  - prettier
plugins:
  - import
  - unused-imports
  - '@typescript-eslint'
parser: '@typescript-eslint/parser'
rules:
  'import/order':
    - warn
    - groups: [ [ 'builtin', 'external', 'internal' ] ]
      newlines-between: never
      alphabetize:
        order: 'desc'
