root: true
env:
  es6: true
  node: true
  browser: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:storybook/recommended
  - next/core-web-vitals
  - prettier
plugins:
  - '@typescript-eslint'
parser: '@typescript-eslint/parser'
