name: general-typeCheck
on:
  pull_request:
    paths:
      - packages/general/**/*
jobs:
  typeCheck:
    name: front-typeCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: using node
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0

      - name: module install
        run: pnpm i --frozen-lockfile

      - name: run typeChecking
        run: pnpm run typeCheck
        working-directory: packages/general
