import React from "react";
import { ThemeRegistry } from "@/components/Theme/ThemeRegistry/ThemeRegistry";
import { Default } from "@/layout/default";
import { AlertProvider } from "@/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

const RootLayout: React.FC<Props> = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  return (
    <html lang="ja">
      <body>
        <ThemeRegistry>
          <AlertProvider>
            <Default>{children}</Default>
          </AlertProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
