name: general-lint
on:
  pull_request:
    paths:
      - packages/general/**/*
jobs:
  lint:
    name: front-lint
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/packageInstall
      - name: lint check
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint-flags: --ext .js,.ts .
          workdir: packages/general
