name: general-typeCheck
on:
  pull_request:
    paths:
      - packages/general/**/*
jobs:
  typeCheck:
    name: front-typeCheck
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/packageInstall
      - name: run typeChecking
        run: pnpm run typeCheck
        working-directory: packages/general
